jsf:
  PROJECT_STAGE: Production
  FACELETS_LIBRARIES: /tags/tags.taglib.xml
  primefaces:
    theme: bootstrap
  bootsfaces:
      usetheme: true
spring:
    jpa:
        database: MYSQL
        show-sql: true
        hibernate:
          ddl-auto: none
    datasource:
        warehouse:
              type: com.zaxxer.hikari.HikariDataSource
              url: jdbc:mysql://${DB_HOST_PORT_WAREHOUSE:localhost:3306}/${DB_SCHEMA_WAREHOUSE:sys}
              username: ${DB_USER:root}
              password: ${DB_PASS:root}
#        url: jdbc:mysql://${DB_HOST_PORT:localhost:3306}/${DB_SCHEMA:pricing_dolon}?autoReconnect=true
#        username: ${DB_USER:root}
#        password: ${DB_PASS:123123}
server:
    port: 8082
    session:
        timeout: -1
logging:
    file: logs/pricing-dolon-dashboard.log
    pattern:
        console: "%d %-5level %logger : %msg%n"
        file: "%d %-5level [%thread] %logger : %msg%n"
    level:
        root: INFO
        org.springframework.web: INFO
        org.hibernate: INFO
#        org.hibernate: trace
